-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') from `MEMBER_PROFILE`
where  `DATE_OF_BIRTH` like "_____03%" and `GENDER`='W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;